include "controlsfx", "fxsampler", "controlsfx-samples", "jdk-jsobject"

buildscript {
    repositories {
        mavenCentral()
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    pluginManagement {
        plugins {
            id 'biz.aQute.bnd.builder' version '7.3.0'
        }
    }
}
